### getPageByPath_success
GET {{HOST}}/api/v1/pages?host=system&page=test-path
Content-Type: {{JSON}}

> {%
    client.test("SHOULD return page data WHEN request is valid", () => {
        client.assert(response.status === 200);

        client.assert(response.body.data !== null);
        client.assert(response.body.data.hostPath !== null);
        client.assert(response.body.data.pageProfile !== null);
        client.assert(response.body.data.pageContents !== null);

        client.assert(response.body.error === null);
    });
%}

### getPageByPath_hostPathNotFound
GET {{HOST}}/api/v1/pages?host=not-found&page=test-path
Content-Type: {{JSON}}

> {%
    client.test("SHOULD return error WHEN host path not found", () => {
        client.assert(response.status === 404);

        client.assert(response.body.data === null);

        client.assert(response.body.error === "user.displayPath.notFound");
    });
%}

### getPageByPath_pagePathNotFound
GET {{HOST}}/api/v1/pages?host=system&page=not-found
Content-Type: {{JSON}}

> {%
    client.test("SHOULD return error WHEN host path not found", () => {
        client.assert(response.status === 404);

        client.assert(response.body.data === null);

        client.assert(response.body.error === "page.displayPath.notFound");
    });
%}