### updatePage_success
POST {{HOST}}/api/v1/pages/01a06669-e82b-779f-beec-a102fde4adf3
Content-Type: {{JSON}}

{
  "displayPath": "test-path-updated",
  "title": "Test title (UPDATED)",
  "description": "Test description. (UPDATED)",
  "access": "PRIVATE"
}

> {%
    client.test("SHOULD return success WHEN using valid page data", () => {
        client.assert(response.status === 200);

        client.assert(response.body === null);
    });
%}

### updatePage_pageIdNotFound
POST {{HOST}}/api/v1/pages/{{BAD_UUID}}
Content-Type: {{JSON}}

{
  "displayPath": "test-path",
  "title": "Test title",
  "description": "Test description.",
  "access": "PUBLIC"
}

> {%
    client.test("SHOULD return error WHEN page ID not found", () => {
        client.assert(response.status === 404);

        client.assert(response.body !== null);
        client.assert(response.body.error === "page.id.notFound");

        client.assert(response.body.data === null);
    });
%}
